"""add_newspaper_model

Revision ID: 8375ffc143c8
Revises: ce6450c4f79e
Create Date: 2026-02-25 19:45:30.015367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8375ffc143c8'
down_revision: Union[str, Sequence[str], None] = 'ce6450c4f79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newspaper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_task_id'], ['news_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newspaper_news_task_id'), 'newspaper', ['news_task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newspaper_news_task_id'), table_name='newspaper')
    op.drop_table('newspaper')
    # ### end Alembic commands ###
